name: Build and Deploy the image to Dockerhub
on: [push]

jobs:
  build:
    name: Build and Deploy image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: z0beat/hello-world
          tags: latest